reporting_interval_secs = 3600

[mqtt]
client_id = "affaldvarme"
host = "10.0.1.3"
port = 1883
username = ""
password = ""


[affaldvarme]
base_url = "https://portal-api.kredslob.dk"

# You can specify either the Id of the address or fully qualify the address
# [affaldvarme.address]
# id = "07514448_100_______"

#[affaldvarme.address]
# street_name = "Kongevejen"
# street_no = "100"
# postal_code = "8000"
# city = "Aarhus C"
# address_lookup_url = "https://api.dataforsyningen.dk"
