on:
  push:
    branches:
      - main
  pull_request:

name: Build

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install nextest
        uses: taiki-e/install-action@v2
        with:
          tool: nextest

      - name: Run unit tests (nextest)
        env:
          CARGO_TERM_COLOR: always
        run: |
          cargo nextest run --profile ci
     
      - name: Report unit test results
        uses: dorny/test-reporter@v1
        if: success() || failure()    # run this step even if previous step failed
        with:          
          path: target/nextest/ci/*.xml
          reporter: java-junit
          max-annotations: 50
          name: Test Suite Summary
  lints:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Run cargo fmt
        run: cargo fmt --all -- --check

      - uses: clechasseur/rs-clippy-check@v3
        with:
          args: --all-features -- -D warnings
  coverage:
    name: Code coverage
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@cargo-llvm-cov
      - uses: taiki-e/install-action@nextest
      - name: Generate code coverage
        run: cargo llvm-cov nextest --all-features --workspace --lcov --output-path lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:          
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
